### ISSUE TITLE
1.처음 진입시  발생하는 문제

### ISSUE THREAD

**Issue by jeongsunyong** [baesy0/DataStructure-Algorithm#2]
for (i = 0; i < n; i++) {
		//printf("n:%d \n", n); *******1번
		scanf_s("%s", str);
		fgetc(stdin);
		if (!strcmp(str, "push")) {
			//printf("test,push"); *******2번
			scanf_s("%d", &num);
			fgetc(stdin);
			push(&qu, num);
		}
		else if (!strcmp(str, "pop")) {
			printf("%d\n", pop(&qu));
		}

우선 첫번째로 돌려봤을 때 back에서 멈추길래 back의 리턴문이 문제인가 했는데
main함수를 테스트해보니
**결과
15
n:15
push 1
n:15
n:15
n:15
n:15
push 2
n:15
n:15
n:15
n:15
front
n:15
n:15
n:15
n:15
back
n:15
n:15
-----종료

1번 -> n이 15로 감소하지 않음(for문이 돌지 않음)

2번 -> 출력되지 않음 ( if문 조건 strcmp 통과 x)

이므로 

push에 걸리지 않고 for문 끝나기 전 어딘가에서 종료되는 것 같고
우선 if 조건문을 수정해봐야 할 것같습니다

**Comment by baesy0** [comment]
1번.
n=15에서 안줄어드는게 맞지 않나요? for문은 n은 가만히 있고, i값이 커져서 n값과 같아지면 for문을 빠져나오는거니까요
2번.
저는 strcmp에 잘 잡혀요! 아마 명령어 입력할 때 대문자, 소문자 차이 때문에 안 잡혔던 게 아닐까 싶어요
ex) Push 3, push 3

**Comment by baesy0** [comment]
해결했어요!!
push했을 때
```
queue[rear] = data
rear++
```
이런 식이었어야 했는데
rear++
queue[rear] = data
이렇게 순서를 바꿔서 첫번째 칸에 값이 안들어갔던 거였어요!
